name: surveyexport

on:
  push:
    branches:
      - testing

jobs:
  my_checks:
    name: test go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: testing
      - name: set up python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.10

      - name: install dependencies
        run: |
          make install
      - name: run tests
        run: |
          make test